# position data can be used to define the robot's pose in a given frame
builtin_interfaces/Time stamp
float64 x           # x position in meters, horizontal direction forward
float64 y           # y position in meters, horizontal direction sideways
float64 z           # z position in meters, vertical direction upwards
float64 yaw_z       # orientation in radians, "yaw". (this means angular rotation pointing upwards from origin turning CCW when looking from origin)