# Request
g425_assign1_interfaces_pkg/Student student
float32[] tentamen_cijfers

---
# Response
g425_assign1_interfaces_pkg/Student student
float32 final_result


## format  <type> <name> <optional_default_value>
##primitive message types
#    bool
#    byte
#    char
#    float32, float64
#    int8, uint8
#    int16, uint16
#    int32, uint32
#    int64, uint64
#    string

